name: Build2

on: 
  push:
    branches:
      - main
    paths:
      - swagger-test/src/main/**  #向swagger-test/src/main路径push代码时触发
  workflow_dispatch:              #手动触发

permissions:
  contents: read                  #读内容的权限，可以使用checkout
  pages: write                    #设置github-pages的权限
  id-token: write                 #设置github-page需要验证id-token的写权限
  
concurrency:
  group: "build"
  cancel-in-progress: true

jobs: 
  buildjava:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4    #获取当前main分支的内容
      with: 
        path: main
    - name: Setup Java
      uses: actions/setup-java@v4    #设置java环境
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven                  #使用maven缓存
    - name: Build with Maven
      run: mvn --file main/swagger-test/pom.xml install
    - name: run jar file
      run: nohup java -jar main/swagger-test/target/swagger-test-1.0.0.jar &
    - name: make dir
      run: mkdir -p temp
    - name: get json file
      run: curl -o temp/swagger.json http://127.0.0.1:8765/v3/api-docs
    - name: Upload artifact for next job #使用upload-artifact上传生成的json，给下一个job使用
      uses: actions/upload-artifact@main
      with:
        name: jsonfile
        path: temp
  buildswagger:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with: 
        path: main
    - name: Checkout swagger-ui
      uses: actions/checkout@v4
      with:
        repository: swagger-api/swagger-ui
        ref: 'v5.2.0'
        path: swagger-ui
    - name: Modify Initializer.js
      run: sed -i 's$"https:\/\/petstore\.swagger\.io\/v2\/swagger\.json"$new URL\(location\)\.searchParams\.get\("q"\) \|\| "swagger\.json"$g' swagger-ui/dist/swagger-initializer.js
    - name: Upload artifact for next job
      uses: actions/upload-artifact@main
      with:
        name: swagger-ui
        path: swagger-ui/dist
  makejsonAndDeploy: 
    needs: [buildjava,buildswagger]
    runs-on: ubuntu-latest
    environment:
      name: github-pages-swagger-ui-java
      url: ${{ steps.deployment.outputs.page_url }}swagger-ui-java
    steps: 
    - name: Download artifact from buildjava job
      uses: actions/download-artifact@main
      with:
        name: jsonfile
        path: swagger-temp/swagger-ui-java
    - name: Download artifact from buildswagger job
      uses: actions/download-artifact@main
      with:
        name: swagger-ui
        path: swagger-temp/swagger-ui-java
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'swagger-temp'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
