name: Build2

on: 
  push:
    branches:
      - main
    paths:
      - swagger-test/src/main/**  #向swagger-test/src/main路径push代码时触发
  workflow_dispatch:              #手动触发

permissions:
  contents: read                  #读内容的权限，可以使用checkout
  pages: write                    #设置github-pages的权限
  id-token: write                 #设置github-page需要验证id-token的写权限
  
concurrency:
  group: "build"
  cancel-in-progress: true

jobs: 
  buildjava:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4    #获取当前main分支的内容
      with: 
        path: main
    - name: Setup Java
      uses: actions/setup-java@v4    #设置java环境
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven                  #使用maven缓存
    - name: Build with Maven          #通过maven编译
      run: mvn --file main/swagger-test/pom.xml package
    - name: run jar file              #运行编译后的jar文件
      run: nohup java -jar main/swagger-test/target/swagger-test-1.0.0.jar &
    - name: make dir                  #创建temp文件夹，保存取得的json文件
      run: mkdir -p temp
    - name: get json file             #访问springdoc中swagger-ui文档接口，下载json文件
      run: curl -o temp/swagger.json http://127.0.0.1:8765/v3/api-docs
    - name: Upload artifact for next job #使用upload-artifact上传生成的json，给下一个job使用
      uses: actions/upload-artifact@v4
      with:
        name: jsonfile
        path: temp
  buildswagger:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout swagger-ui       #checkout swagger-ui仓库,获取dist下的静态资源
      uses: actions/checkout@v4
      with:
        repository: swagger-api/swagger-ui
        ref: 'v5.2.0'
        path: swagger-ui
    - name: Modify Initializer.js       #修改swagger-initializer.js，替换使用的json文件
      run: sed -i 's$"https:\/\/petstore\.swagger\.io\/v2\/swagger\.json"$new URL\(location\)\.searchParams\.get\("q"\) \|\| "swagger\.json"$g' swagger-ui/dist/swagger-initializer.js
    - name: Upload artifact for next job #使用upload-artifact上传生成的json，给下一个job使用
      uses: actions/upload-artifact@v4
      with:
        name: swagger-ui
        path: swagger-ui/dist
  makejsonAndDeploy: 
    needs: [buildjava,buildswagger]       #需要前两个job执行后才能执行
    runs-on: ubuntu-latest
    environment:
      name: github-pages-swagger-ui-java   #定义环境名称
      url: ${{ steps.deployment.outputs.page_url }}swagger-ui-java  #访问环境的url
    steps: 
    - name: Download artifact from buildjava job    #下载取得的json文件
      uses: actions/download-artifact@v4
      with:
        name: jsonfile
        path: swagger-temp/swagger-ui-java
    - name: Download artifact from buildswagger job #下载修改后的swagger-ui静态资源文件
      uses: actions/download-artifact@v4
      with:
        name: swagger-ui
        path: swagger-temp/swagger-ui-java
    - name: Setup Pages                              #配置使用github-pages
      uses: actions/configure-pages@v4
    - name: Upload artifact                          #将静态资源上传至github-pages服务器
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'swagger-temp'
    - name: Deploy to GitHub Pages                    #部署github-pages
      id: deployment
      uses: actions/deploy-pages@v4
