server:
  port: 8765
spring:
  application:
    name: swagger-test
# swagger-ui custom path
springdoc:
#  swagger-ui:
#    path : /swagger-ui.html #默认swaggerUI路径，可通过配置更改
  packages-to-scan: 
    - com.test #指定哪些包下的接口被扫描，如果不指定会将引入的所有接口扫描，包括依赖包如base包中的共通接口